"""new fields in user model

Revision ID: 736ce9108c3f
Revises: 99d78c3ac5f8
Create Date: 2018-04-09 13:12:03.684943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736ce9108c3f'
down_revision = '99d78c3ac5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
